import type { Metadata } from "next";
import { Inter, Bruno_Ace } from "next/font/google";
import "@/styles/globals.css";

const brunoAce = Bruno_Ace({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Study smart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${brunoAce.className} bg-dark-primary text-white overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
